EXPORT.radius = module.ProfileMapping(...
	@(obj) obj.data.radius,...
	'r' ...
);

EXPORT.mass = module.ProfileMapping(...
	@(obj) obj.data.mass,...
	'M(r)'...
);

EXPORT.velocity = module.ProfileMapping(...
	@(obj) obj.data.velocity,...
	'v(r)'...
);