EXPORT.radius = module.ProfileMapping(...
	@(obj) obj.data.radius,...
	'r' ...
);

EXPORT.velocity = module.ProfileMapping(...
	@(obj) obj.data.velocity,...
	'v(r)'...
);

EXPORT.velocity_error = module.ProfileMapping(...
	@(obj) obj.data.velocity_error,...
	'\Delta v(r)'...
);

EXPORT.acceleration = module.ProfileMapping(...
	@(obj) obj.data.velocity.^2./obj.data.radius,...
	'a(r)'...
);

EXPORT.mass = module.ProfileMapping(...
	@(obj) obj.data.radius.*obj.data.velocity.^2,...
	'v(r)'...
);

EXPORT.mass_error = module.ProfileMapping(...
	@(obj) (obj.data.radius_error./obj.data.radius + 2*obj.data.velocity_error./obj.data.velocity).*EXPORT.mass.map(obj),...
	'v(r)'...
);